### PR TITLE
updating readme and adding additional development details #31

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
I'm unsure why there are conflicts, but the files have been updated.

**Comment by bfitzpat** [comment]
Also - tried doing an interactive rebase to change the git message to refer to #33 instead of #31 but I keep seeing "noop" in the command line when I give that a go.

**Comment by apupier** [comment]
I think there are conflicts because this branch is based on your remote master branch but not on the Camel Tooling master branch.
You need to rebase on Camel tooling master branch. You will have a conflict to resolve. Then commit with the resolved conflict and finally force push.

> Also - tried doing an interactive rebase to change the git message to refer to #32 instead of #31 but I keep seeing "noop" in the command line when I give that a go.

can you precise on which commit you called the interactive rebase?
have you tried using Egit interface, with right-click on the commit, then Modify -> reword ?

**Comment by bfitzpat** [comment]
Rebasing on upstream master did the trick. Thanks.

**Comment by bfitzpat** [comment]
Once we get https://github.com/camel-tooling/generator-camel-project/pull/31 finished up, we can get this one merged too.

**Comment by bfitzpat** [comment]
Updated readme with new wsdl2rest details and list of known issues

**Pull request merged**
